name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
#     - run: flutter build web
#     - run: flutter build apk
#     - run: flutter build apk --debug --split-per-abi
#     - run: flutter build apk --release --split-per-abi
    - name: Build APK
      run: flutter build apk

    - name: Copy APK To Parent Directory
      run: cp ./build/app/outputs/flutter-apk/app-release.apk ./app.apk

    - name: Commit APK
      run: git add ./app.apk

    - name: Configure Github
      run: |
          git config --local user.email "you@email.com"
          git config --local user.name "yourusername"
          git commit -m "Generated APK" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.FFD }}
#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#           GITHUB_TOKEN: ${{ secrets.FFD }} # This token is provided by Actions, you do not need to create your own token
#       with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           body: |
#             Release
#           draft: false
#           prerelease: false
#     - uses: actions/upload-artifact@v1
#       with:
#         name: release-apk
#         path: build/app/outputs/apk/release/app-release.apk
